"""gen_sci.py — regenerate src/sci.zbr from a Scintilla.h.

    py tools/gen_sci.py path/to/Scintilla.h > src/sci.zbr

Stdlib only. Emits `const NAME = value` for every name in WANT that the header
defines as a plain integer; prints names it could not find to stderr (SCI_SETLEXER
is gone in Scintilla 5 — SCI_SETILEXER replaces it — so that one is expected).
"""
import re, sys

WANT = """
SCI_SETTEXT SCI_GETTEXT SCI_GETLENGTH SCI_GETCURRENTPOS SCI_SETCURRENTPOS SCI_GOTOLINE SCI_GOTOPOS SCI_GETLINECOUNT
SCI_LINEFROMPOSITION SCI_POSITIONFROMLINE SCI_GETLINE SCI_LINELENGTH SCI_GETCOLUMN SCI_FINDCOLUMN
SCI_SETSEL SCI_GETSELECTIONSTART SCI_GETSELECTIONEND SCI_SETSELECTIONSTART SCI_SETSELECTIONEND SCI_GETSELTEXT SCI_REPLACESEL
SCI_INSERTTEXT SCI_DELETERANGE SCI_CLEARALL SCI_SETSAVEPOINT SCI_GETMODIFY SCI_UNDO SCI_REDO SCI_CANUNDO SCI_CANREDO SCI_EMPTYUNDOBUFFER
SCI_SETREADONLY SCI_GETREADONLY SCI_GETFIRSTVISIBLELINE SCI_SETFIRSTVISIBLELINE SCI_LINESONSCREEN SCI_SCROLLCARET SCI_ENSUREVISIBLE
SCI_MARKERDEFINE SCI_MARKERSETFORE SCI_MARKERSETBACK SCI_MARKERSETALPHA SCI_MARKERSETLAYER SC_LAYER_UNDER_TEXT SCI_MARKERADD SCI_MARKERDELETE SCI_MARKERDELETEALL SCI_MARKERGET SCI_MARKERNEXT SCI_MARKERPREVIOUS
SCI_SETMARGINTYPEN SCI_SETMARGINWIDTHN SCI_GETMARGINWIDTHN SCI_SETMARGINMASKN SCI_SETMARGINSENSITIVEN SCI_SETMARGINS
SCI_INDICSETSTYLE SCI_INDICSETFORE SCI_INDICSETUNDER SCI_SETINDICATORCURRENT SCI_INDICATORFILLRANGE SCI_INDICATORCLEARRANGE
SCI_ANNOTATIONSETTEXT SCI_ANNOTATIONSETSTYLE SCI_ANNOTATIONCLEARALL SCI_ANNOTATIONSETVISIBLE
SCI_STYLESETFORE SCI_STYLESETBACK SCI_STYLESETBOLD SCI_STYLESETITALIC SCI_STYLESETFONT SCI_STYLESETSIZE SCI_STYLECLEARALL SCI_STYLERESETDEFAULT
SCI_SETLEXER SCI_SETILEXER SCI_SETKEYWORDS SCI_STARTSTYLING SCI_SETSTYLING SCI_GETENDSTYLED SCI_COLOURISE SCI_GETSTYLEAT
SCI_SETTARGETSTART SCI_SETTARGETEND SCI_SETTARGETRANGE SCI_SEARCHINTARGET SCI_REPLACETARGET SCI_SETSEARCHFLAGS SCI_TARGETFROMSELECTION
SCI_SETCODEPAGE SCI_SETTABWIDTH SCI_SETUSETABS SCI_SETINDENT SCI_SETEOLMODE SCI_CONVERTEOLS SCI_SETVIEWWS SCI_SETVIEWEOL
SCI_SETCARETLINEVISIBLE SCI_SETCARETLINEBACK SCI_SETZOOM SCI_ZOOMIN SCI_ZOOMOUT SCI_SETWRAPMODE SCI_SETHSCROLLBAR
SCI_AUTOCSHOW SCI_AUTOCCANCEL SCI_AUTOCACTIVE SCI_AUTOCSETSEPARATOR SCI_CALLTIPSHOW SCI_CALLTIPCANCEL SCI_CALLTIPACTIVE
SCI_BRACEHIGHLIGHT SCI_BRACEBADLIGHT SCI_BRACEMATCH SCI_SETFOLDLEVEL SCI_GETFOLDLEVEL SCI_TOGGLEFOLD SCI_SETFOLDFLAGS
SCI_GETDIRECTFUNCTION SCI_GETDIRECTPOINTER SCI_GETCHARAT SCI_POSITIONBEFORE SCI_POSITIONAFTER SCI_WORDSTARTPOSITION SCI_WORDENDPOSITION
SCI_SETMULTIPLESELECTION SCI_SETADDITIONALSELECTIONTYPING
SCI_CREATEDOCUMENT SCI_ADDREFDOCUMENT SCI_RELEASEDOCUMENT SCI_GETDOCPOINTER SCI_SETDOCPOINTER SCI_GETSELECTIONSTART SCI_SETEMPTYSELECTION SCI_SETXOFFSET SCI_GETXOFFSET
SC_MARK_CIRCLE SC_MARK_ARROW SC_MARK_SMALLRECT SC_MARK_SHORTARROW SC_MARK_BACKGROUND SC_MARK_FULLRECT SC_MARK_BOOKMARK
SC_MARGIN_SYMBOL SC_MARGIN_NUMBER SC_MARGIN_TEXT SC_MARGIN_BACK SC_MARGIN_FORE
INDIC_SQUIGGLE INDIC_PLAIN INDIC_STRAIGHTBOX INDIC_ROUNDBOX INDIC_FULLBOX INDIC_TEXTFORE INDIC_HIDDEN
STYLE_DEFAULT STYLE_LINENUMBER STYLE_BRACELIGHT STYLE_BRACEBAD STYLE_INDENTGUIDE STYLE_CALLTIP
SCFIND_MATCHCASE SCFIND_WHOLEWORD SCFIND_REGEXP SCFIND_WORDSTART SC_EOL_CRLF SC_EOL_LF SC_WRAP_NONE SC_WRAP_WORD
ANNOTATION_HIDDEN ANNOTATION_STANDARD ANNOTATION_BOXED SC_CP_UTF8
SCN_STYLENEEDED SCN_CHARADDED SCN_SAVEPOINTREACHED SCN_SAVEPOINTLEFT SCN_MODIFIED SCN_UPDATEUI SCN_MARGINCLICK SCN_DWELLSTART SCN_DWELLEND SCN_ZOOM
SC_MOD_INSERTTEXT SC_MOD_DELETETEXT SC_MOD_CHANGESTYLE SC_MOD_CHANGEMARKER SC_MOD_CHANGEFOLD SC_PERFORMED_USER SC_PERFORMED_UNDO SC_PERFORMED_REDO
""".split()

HEADER = """\
# sci.zbr — Scintilla message and constant ids for the editor.sci()/sciStr() hatch.
# Generated from Scintilla 5.5.2 include/Scintilla.h (the copy vendored by bindings_libui_ng)
# by zebra-ide/tools/gen_sci.py — do not hand-edit; regenerate when Scintilla moves.
# Subset: the messages the IDE plan (PLAN.md §3) needs. Add names to the WANT list to extend.
#
# Usage:  use sci exposing SCI_GOTOLINE, SCI_MARKERADD
#         var n = editor.sci(SCI_GETLENGTH, 0, 0)
#         editor.sciStr(SCI_SETTEXT, 0, text)
# Hatch return is i64 (raw sptr_t): pointers/lengths come back untouched; on the TUI backend every call returns 0.
"""

def main(path):
    found = {}
    for line in open(path, encoding="utf-8", errors="replace"):
        m = re.match(r"#define (\w+) (\d+|0x[0-9a-fA-F]+)\s*$", line)
        if m and m.group(1) in WANT:
            found[m.group(1)] = int(m.group(2), 0)
    missing = sorted(set(WANT) - found.keys())
    out = [HEADER]
    for k in sorted(found, key=lambda k: (k.split("_")[0], found[k])):
        out.append(f"const {k} = {found[k]}")
    sys.stdout.write("\n".join(out) + "\n")
    if missing:
        print("not found in header:", " ".join(missing), file=sys.stderr)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
